version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root009@host.docker.internal:3306/url_shortener_db
      - JWT_SECRET_KEY=your-super-secret-key
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always